name = "appchahiye-smart-web-apps-for-smarter-businesses"
main = "worker/index.ts"
compatibility_date = "2025-04-24"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "appchahiye"

[vars]
R2_PUBLIC_URL = "https://appchahiye.com/appchahiye"

routes = [
  { pattern = "appchahiye.com/*", zone_name = "appchahiye.com" }
]
